[VARIABLE_DECLARATION]
keyword = ["let", "const", "var"]

[IF]
keyword = ["if"]

[ELSE]
keyword = ["else"]

[FOR]
keyword = ["for"]

[NUMBER_LITERAL]
test = "(0[x|X])?[0-9A-F]"

[ID]
test = "[a-zA-Z_][a-zA-Z_0-9]*"
